Execute SDO_CS.TRANSFORM_LAYER('WALKS','GEOM','WALKS_BNG', 81989)
/
Execute SDO_CS.TRANSFORM_LAYER('PUBS','GEOM','PUBS_BNG', 81989)
/
Execute SDO_CS.TRANSFORM_LAYER('PARKING','GEOM','PARKING_BNG', 81989)
/
Execute SDO_CS.TRANSFORM_LAYER('MUNROS','GEOM','MUNROS_BNG', 81989)
/
