CREATE TABLE MUNROS
(MUNRO_ID NUMBER(3),
NAME VARCHAR(255),
HEIGHT DECIMAL(6,2) CHECK(HEIGHT BETWEEN 914 AND 1344),
XCOORD DECIMAL(10,8) NOT NULL,
YCOORD DECIMAL(10,8) NOT NULL,
COMMENTS VARCHAR(255),
WALKER NUMBER(2) CHECK(WALKER BETWEEN 1 AND 3),
REGION NUMBER(2),
PRIMARY KEY(MUNRO_ID),
FOREIGN KEY(WALKER) REFERENCING WALKERS(WALKER)
FOREIGN KEY(REGION) REFERENCING REGIONS(REGION_ID))
/
