CREATE TABLE REGIONS
(REGION_ID NUMBER(3) NOT NULL,
NAME VARCHAR(40),
GEOM MDSYS.SDO_GEOMETRY,
MIN_TEMP DECIMAL(4,2) CHECK(MIN_TEMP BETWEEN -20 AND 40),
AVG_WIND DECIMAL(4,2) CHECK(AVG_WIND BETWEEN 0 AND 30),
AVG_PRECIP DECIMAL(6,2) CHECK(AVG_PRECIP BETWEEN 0 AND 2000),
PRIMARY KEY(REGION_ID))
/
