CREATE TABLE WALKS
(WALK_ID NUMBER(3) NOT NULL,
LENGTH DECIMAL(5,2),
GEOM MDSYS.SDO_GEOMETRY,
POPULARITY NUMBER(2) CHECK(POPULARITY BETWEEN 1 AND 5),
DIFFICULTY NUMBER(2) CHECK(DIFFICULTY BETWEEN 1 AND 5),
PRIMARY KEY(WALK_ID))
/
