LOAD DATA
INFILE Car Park.csv
REPLACE
INTO TABLE s2559258.parking
FIELDS TERMINATED BY 'X'09'
Record 1: Rejected - Error on table S2559258.MUNROS, column NAME.
TRAILING NULLCOLS
(PARKING,NAME, AREA, GEOM)

